package gui;
import static database.UserData.getAllUserData;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.MimetypesFileTypeMap;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author harsh
 */
public class WelcomeUser extends javax.swing.JFrame {
    private String Email,Filename;

    /**
     * Creates new form WelcomeUser
     */
    public WelcomeUser() {
        initComponents();
        setIcon();
        settingpage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        username5 = new javax.swing.JLabel();
        username6 = new javax.swing.JLabel();
        username8 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        settingpage = new javax.swing.JPanel();
        delete = new javax.swing.JLabel();
        addimage = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setPreferredSize(new java.awt.Dimension(436, 558));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 310, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Your Information");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 375, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 380, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/tenor.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 210, 230));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Welcome");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 290, -1));

        fullname.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        fullname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullname.setText("Username");
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 375, 40));

        username3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        username3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        username3.setText("Username");
        jPanel1.add(username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 110, 40));

        password.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 310, 40));

        username5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        username5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        username5.setText("Email ID");
        jPanel1.add(username5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 110, 40));

        username6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        username6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        username6.setText("Password");
        jPanel1.add(username6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 110, 40));

        username8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        username8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        username8.setText("Birth Date");
        jPanel1.add(username8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 110, 40));

        date.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 310, 40));

        email.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 310, 40));

        setting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-settings-30.png"))); // NOI18N
        setting.setToolTipText("");
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingMouseClicked(evt);
            }
        });
        jPanel1.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 560));

        settingpage.setBackground(new java.awt.Color(255, 255, 255));
        settingpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete.setBackground(new java.awt.Color(255, 255, 204));
        delete.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 0, 0));
        delete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        delete.setText("Delete your account");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        settingpage.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 380, -1));

        addimage.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        addimage.setForeground(new java.awt.Color(0, 255, 0));
        addimage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addimage.setText("Add profile image");
        addimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addimageMouseClicked(evt);
            }
        });
        settingpage.add(addimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 390, -1));

        logout.setBackground(new java.awt.Color(255, 255, 204));
        logout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(51, 102, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        settingpage.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 375, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-macos-close-100.png"))); // NOI18N
        jLabel8.setToolTipText("Close setting");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        settingpage.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Settings");
        settingpage.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 390, -1));

        getContentPane().add(settingpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 560));

        setSize(new java.awt.Dimension(454, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseClicked
        settingpage.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_settingMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        HomeForm hf = new HomeForm();
        hf.setVisible(true);
        this.dispose();
        this.setVisible(false);        
    }//GEN-LAST:event_logoutMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        settingpage.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        int a = JOptionPane.showConfirmDialog(this, "All your account information will be deleted\n"
                + "You will not be able to login");
        if (a == JOptionPane.YES_OPTION) {
            deleteAccount(email.getText());
            HomeForm hf = new HomeForm();
            hf.setVisible(true);
            this.dispose();
            this.setVisible(false);
        }
    }//GEN-LAST:event_deleteMouseClicked

    @SuppressWarnings("empty-statement")
    private void addimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addimageMouseClicked
        getFileName();
        System.out.println(Filename);
        if (isImage(Filename)) {
            try {
                validater.CompressImage.resize(Filename, "profileimage.jpg", 400, 400);
                if (imgInDB(email.getText())); else {
                    deleteImage();
                }
            } catch (IOException ex) {
                Logger.getLogger(WelcomeUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an image..");
        }
    }//GEN-LAST:event_addimageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addimage;
    private javax.swing.JLabel date;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel password;
    private javax.swing.JLabel setting;
    private javax.swing.JPanel settingpage;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username5;
    private javax.swing.JLabel username6;
    private javax.swing.JLabel username8;
    // End of variables declaration//GEN-END:variables

 private void setIcon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    public void getData(String Email) {
        String[] userinfo;
        userinfo = getAllUserData(Email);
        fullname.setText(userinfo[0] +" "+userinfo[1]);
        username.setText(userinfo[3]);
        password.setText(userinfo[5]);
        email.setText(userinfo[2]);
        Email = email.getText();
        date.setText(userinfo[4]);
    }

    private void deleteAccount(String Email) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "8850");
            String q = "delete from userdatatest where email=?";
            PreparedStatement ps = con.prepareStatement(q);
            ps.setString(1, email.getText());
            ps.executeUpdate();
            Statement st = con.createStatement();
            st.executeUpdate("delete from imageDB where email='" + Email + "'");
            JOptionPane.showMessageDialog(this, "Your account has been deleted");
            HomeForm hf = new HomeForm();
            hf.setVisible(true);
            con.close();
        } catch (SQLException sq) {
            System.out.println("Error");
            JOptionPane.showMessageDialog(this, "Email address already in use");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(WelcomeUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void userProfileIcon(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/mydb", "root", "8850");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select profileimage from imageDB where email='" + email.getText() + "'");
            if (rs.next()) {
                byte[] img1 = rs.getBytes("profileimage");
                ImageIcon icon = new ImageIcon(img1);
                Image img = icon.getImage();
                Image simg = img.getScaledInstance(210, 230, Image.SCALE_SMOOTH);
                ImageIcon pimg = new ImageIcon(simg);
                if (pimg != null) {
                    jLabel3.setIcon(pimg);
                }
                con.close();
            } else {
                con.close();
            }
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        }
    }
     
    private void getFileName()
     {  
         try {
             JFileChooser chooser = new JFileChooser();
             chooser.showOpenDialog(null);
             File f = chooser.getSelectedFile();
             Filename = f.getAbsolutePath();
         } catch (NullPointerException e) {
             System.out.println("Not selected");
         }
      }
    
    private boolean isImage(String filename)
    {
        try {
            File f = new File(filename);
            String mimetype = new MimetypesFileTypeMap().getContentType(f);
            String type = mimetype.split("/")[0];
            if (type.equals("image")) {
                return true;
            } else {
                return false;
            }
        } catch (NullPointerException e) {
            System.out.println("Not selected an image");
            return false;
        }
    }
    
    public void deleteImage()
    {
        File del = new File("profileimage.jpg");
        del.delete();
    }
    public boolean imgInDB(String email) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "8850");
            File f = new File("profileimage.jpg");
            FileInputStream fis = new FileInputStream(f);
            PreparedStatement ps = con.prepareStatement("update imageDB set profileimage=? where email=?");
            ps.setBinaryStream(1, fis, (int) f.length());
            ps.setString(2, email);
            ps.executeUpdate();
            fis.close();
            ps.close();
            con.close();
            userProfileIcon();
            deleteImage();
            return true;
        } catch (Exception e) {
            System.out.println("Image NOT in DB");
            System.out.println(e);
            return false;
        }
    }
}
